from .src.core.llm_loader import NODE_CLASS_MAPPINGS as LLM_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LLM_LOADER_DISPLAY_MAPPINGS
from .src.core.openai_compatible import NODE_CLASS_MAPPINGS as OPENAI_COMPATIBLE_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OPENAI_COMPATIBLE_LOADER_DISPLAY_MAPPINGS
from .src.processors.image_processor import NODE_CLASS_MAPPINGS as IMAGE_PREPROCESSOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_PREPROCESSOR_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **LLM_LOADER_MAPPINGS,
    **OPENAI_COMPATIBLE_LOADER_MAPPINGS,
    **IMAGE_PREPROCESSOR_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LLM_LOADER_DISPLAY_MAPPINGS,
    **OPENAI_COMPATIBLE_LOADER_DISPLAY_MAPPINGS,
    **IMAGE_PREPROCESSOR_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
